// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppArrayFire.h"
#include <Rcpp.h>

using namespace Rcpp;

// arrayfire_device_prop
Rcpp::List arrayfire_device_prop();
RcppExport SEXP RcppArrayFire_arrayfire_device_prop() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List __result = arrayfire_device_prop();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// arrayfire_set_device
void arrayfire_set_device(const int index);
RcppExport SEXP RcppArrayFire_arrayfire_set_device(SEXP indexSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const int >::type index(indexSEXP );
        arrayfire_set_device(index);
    }
    return R_NilValue;
END_RCPP
}
// arrayfire_get_device
int arrayfire_get_device();
RcppExport SEXP RcppArrayFire_arrayfire_get_device() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        int __result = arrayfire_get_device();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// arrayfire_count_device
int arrayfire_count_device();
RcppExport SEXP RcppArrayFire_arrayfire_count_device() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        int __result = arrayfire_count_device();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
