# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Report the information about current device and platform
#' @details Return a list contains the informations about current device and platform.
#' The list object include device name, palatform information, toolkit information, 
#' and compute capability.
#' @return List contains the information about device and platform.
#' @export
#' @references \url{http://arrayfire.org/docs/group__device__func__prop.htm#gaa9eab56ddac21650581682912ea78293}
arrayfire_device_info <- function() {
    .Call(`_RcppArrayFire_arrayfire_device_info`)
}

#' Switch to specified device 
#' @param index the index of a device switched to.
#' @details Available indices
#' can be obtained by calling \code{\link{arrayfire_count_device}}.
#' @export 
#' @references \url{http://arrayfire.org/docs/group__device__func__set.htm#gafbb906ca5b89ec43fdb0e3a14d1df1e7}
arrayfire_set_device <- function(index) {
    invisible(.Call(`_RcppArrayFire_arrayfire_set_device`, index))
}

#' Return the index of current device 
#' @details Get the index of current device which is lower or
#' equal to a value returned by \code{\link{arrayfire_count_device}}.
#' @return the index of current device.
#' @export 
#' @references \url{http://arrayfire.org/docs/group__device__func__get.htm#ga4dfe3f90475b735384f8b28cf2b19a11}
arrayfire_get_device <- function() {
    .Call(`_RcppArrayFire_arrayfire_get_device`)
}

#' Return the number of available devices
#' @details Return the number of available devices.
#' @return the number of available devices. 
#' @export 
#' @references \url{http://arrayfire.org/docs/group__device__func__count.htm#gac3c8750da69ee883fd14c0a8290e45f1}
arrayfire_count_device <- function() {
    .Call(`_RcppArrayFire_arrayfire_count_device`)
}

