# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Report the information about current device and platform
#' @details Return a list contains the informations about current device and platform.
#' The list object include device name, palatform information, toolkit information, 
#' and compute capability.
#' @return List contains the information about device and platform.
#' @export
#' @references \url{http://www.arrayfire.com/docs/group__device__mat.htm#gafae79277ec9ce681976c48392985baf0}  
arrayfire_device_prop <- function() {
    .Call('RcppArrayFire_arrayfire_device_prop', PACKAGE = 'RcppArrayFire')
}

#' Switch to specified device 
#' @param index the index of a device switched to.
#' @details Available indices
#' can be obtained by calling \code{\link{arrayfire_count_device}}.
#' @export 
#' @references \url{http://www.arrayfire.com/docs/group__device__mat.htm#ga6473f398cab654fc0bef97833a5bea5f}  
arrayfire_set_device <- function(index) {
    invisible(.Call('RcppArrayFire_arrayfire_set_device', PACKAGE = 'RcppArrayFire', index))
}

#' Return the index of current device 
#' @details Get the index of current device which is lower or
#' equal to a value returned by \code{\link{arrayfire_count_device}}.
#' @return the index of current device.
#' @export 
#' @references \url{http://www.arrayfire.com/docs/group__device__mat.htm#ga6d1964af8b32ca9c2f9525bf5ef8112a}
arrayfire_get_device <- function() {
    .Call('RcppArrayFire_arrayfire_get_device', PACKAGE = 'RcppArrayFire')
}

#' Return the number of available devices
#' @details Return the number of available devices.
#' @return the number of available devices. 
#' @export 
#' @references \url{http://www.arrayfire.com/docs/group__device__mat.htm#ga6d1964af8b32ca9c2f9525bf5ef8112a}
arrayfire_count_device <- function() {
    .Call('RcppArrayFire_arrayfire_count_device', PACKAGE = 'RcppArrayFire')
}

